/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qKCnDrnBdLnY5FSxmB1L78
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsmomr63UV9CFx } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: MOMR63uV9cFX/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsmomr63UV9CFx
});
